feat: va
many-things/cw-hyperlane pull request #21
Opened 2023-07-16 14:34 UTC by byeongsu-hong

2023-07-17 05:24 UTC, hashableric approved these changes

2023-07-17 05:24 UTC, hashableric commented on contracts/va/src/contract.rs
> +    HRP.save(deps.storage, &msg.hrp)?;
This is url prefix, right? Please follow other contracts convention - Prefix.

2023-07-17 05:26 UTC, hashableric requested changes
sorry i misreviewed.

2023-07-17 10:34 UTC, byeongsu-hong commented on contracts/va/src/contract.rs
> +    HRP.save(deps.storage, &msg.hrp)?;
nope it's Human Readable Prefix, HRP.

2023-07-18 06:27 UTC, hashableric approved these changes

2023-07-18 08:32 UTC, merged