(WIP) test: ism_multisig
many-things/cw-hyperlane pull request #9
Opened 2023-06-20 04:38 UTC by hashableric

2023-06-20 17:15 UTC, byeongsu-hong requested changes

2023-06-20 17:15 UTC, byeongsu-hong commented on Cargo.toml
> +sha2 = { version = "0.10.6", default-features = false }
```suggestion
sha2 = { version = "0.10.6", default-features = false }
secp256k1 = "0.27.0"
```

2023-06-20 17:15 UTC, byeongsu-hong commented on contracts/ism-multisig/Cargo.toml
> +secp256k1 = "0.27.0"
```suggestion
secp256k1 = { workspace = true }
```
...and can you move this line to above? it'll be good to specify the other workspace packages

2023-06-20 17:15 UTC, byeongsu-hong commented on contracts/ism-multisig/src/contract.rs
> +        } => query::get_verify(deps, raw_metadata, raw_message),
how about using verify_message?

2023-06-20 17:15 UTC, byeongsu-hong commented on contracts/ism-multisig/src/error.rs
> +    WrongLength {},
It is redundant to use `{}` to enum that does not contains any field

2023-06-20 17:15 UTC, byeongsu-hong commented on packages/interface/src/types/message.rs
> +        let encode_expected: HexBinary = HexBinary::from_hex("00000021500000aef3000000000000000000000000477d860f8f41bc69ddd32821f2bf2c2af0243f1600aa36a70000000000000000000000005d56b8a669f50193b543194
redundant type declaration

2023-06-20 17:16 UTC, byeongsu-hong commented
Can you declare the issue like this? closes MITO-17

2023-06-20 17:46 UTC, hashableric commented on packages/interface/src/types/message.rs
> +        let encode_expected: HexBinary = HexBinary::from_hex("00000021500000aef3000000000000000000000000477d860f8f41bc69ddd32821f2bf2c2af0243f1600aa36a70000000000000000000000005d56b8a669f50193b543194
i didnt realize i fix it :(

2023-06-20 17:47 UTC, byeongsu-hong requested changes

2023-06-20 17:47 UTC, byeongsu-hong commented on contracts/ism-multisig/Cargo.toml
> +secp256k1 = { workspace = true }
```suggestion
```

2023-06-20 17:47 UTC, byeongsu-hong commented on contracts/ism-multisig/Cargo.toml
>  cosmwasm-schema = { workspace = true }
```suggestion
cosmwasm-schema = { workspace = true }
secp256k1 = { workspace = true }
```

2023-06-21 04:31 UTC, steve806 approved these changes

2023-06-21 04:43 UTC, byeongsu-hong approved these changes

2023-06-21 04:43 UTC, merged